import QtQuick 2.15
import OmniUI 1.0
import OmniPhysics 1.0
import OmniGfx 1.0

ApplicationWindow {
    visible: true
    width: 800
    height: 600
    title: "Physics & Shaders"

    ShaderEffect {
        anchors.fill: parent
        // Generated by ShaderGenerator in real app
        fragmentShader: "void main() { gl_FragColor = vec4(0.1, 0.1, 0.2, 1.0); }"
    }

    PhysicsWorld {
        id: physics
        anchors.fill: parent
        running: true
        gravity: 9.81

        Repeater {
            model: 10
            RigidBody {
                x: Math.random() * 700 + 50
                y: Math.random() * -500
                width: 50; height: 50
                mass: 1.0
                restitution: 0.7

                Rectangle {
                    anchors.fill: parent
                    color: "orange"
                    radius: 25
                    border.color: "white"
                    border.width: 2
                }
            }
        }

        // Floor
        RigidBody {
            x: 0; y: 550
            width: 800; height: 50
            isStatic: true
            restitution: 0.5

            Rectangle {
                anchors.fill: parent
                color: "gray"
            }
        }
    }

    MouseArea {
        anchors.fill: parent
        onClicked: {
            // Spawn dynamic body at click
            var comp = Qt.createComponent("Ball.qml");
            // In real app, we'd use dynamic object creation connected to PhysicsWorld
        }
    }
}
